---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pdb-admin
  namespace: events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: events-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: pdb-admin
  namespace: events
